steps:
  - name: "gcr.io/cloud-builders/git"
    args:
      [
        "clone",
        "--recurse-submodules",
        "http://github.com/${_PROJECT}/${_REPO_NAME}",
      ]

  - name: "docker/compose:1.15.0"
    args: ["-f", "/docker/docker-compose.yml", "up", "-d"]
    env:
      - "PROJECT_ID=$PROJECT_ID"

substitutions:
  _PROJECT: Smart-Pot
  _REPO_NAME: smartpot
