steps:
  - name: "gcr.io/cloud-builds/git"
    args:
      [
        "clone",
        "--recurse-submodules",
        "http://github.com/${_PROJECT}/${_REPO}",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcb-docker-compose:latest", "."]

  - name: "docker/compose:1.15.0"
    args: ["up", "-f", "./docker/docker-compose.yml", "-d"]
    env:
      - "PROJECT_ID=$PROJECT_ID"

substitutions:
  _PROJECT: Smart-Pot
  _REPO_NAME: smartpot
